### ISSUE TITLE
to view rand(1000,512) takes ages now 0.2.0

### ISSUE THREAD

**Issue by postoroniy** [timholy/ImageView.jl#101]
using ImageView
x=rand(1000,512)
@time view(x)
WARNING: convert(::Type{UInt32},c::RGB24) is deprecated, use reinterpret(UInt32,c) instead.
 in depwarn at deprecated.jl:73
 in convert at deprecated.jl:50
 in _map_a! at /home/slava/.julia/v0.4/Images/src/map.jl:492
 in uint32color! at /home/slava/.julia/v0.4/Images/src/map.jl:673
 in anonymous at /home/slava/.julia/v0.4/ImageView/src/display.jl:310
 in rerender at /home/slava/.julia/v0.4/ImageView/src/display.jl:681
 in view at /home/slava/.julia/v0.4/ImageView/src/display.jl:316
while loading no file, in expression starting on line 155
 28.170384 seconds (41.86 M allocations: 306.756 GB, 11.71% gc time)
(ImageCanvas,ImageSlice2d: zoom = Graphics.BoundingBox(0.0,512.0,0.0,1000.0))

ImageView 0.2.0
julia 0.4.6

**Comment by postoroniy** [comment]
same for julia 0.5.0

**Comment by postoroniy** [comment]
looks like it's happen due to tonnes of deprecation warnings 
WARNING: convert(::Type{UInt32},c::ColorTypes.RGB24) is deprecated, use reinterpret(UInt32,c) instead.
 in depwarn at deprecated.jl:73
 in convert at deprecated.jl:50
 in _map_a! at /home/slava/.julia/v0.4/Images/src/map.jl:492
 in uint32color! at /home/slava/.julia/v0.4/Images/src/map.jl:673
 in anonymous at /home/slava/.julia/v0.4/ImageView/src/display.jl:310
 in rerender at /home/slava/.julia/v0.4/ImageView/src/display.jl:681
 in view at /home/slava/.julia/v0.4/ImageView/src/display.jl:316

and it does not matter 0.2.0 or master branch

**Comment by timholy** [comment]
Fixed by https://github.com/timholy/Images.jl/pull/564
