### ISSUE TITLE
Error on gray image

### ISSUE THREAD

**Issue by postoroniy** [timholy/ImageView.jl#102]
when I tried how contrast is working I see error below
julia> using ImageView;x=rand(512,512);@time ImageView.view(x)
WARNING: convert(::Type{UInt32},c::ColorTypes.RGB24) is deprecated, use reinterpret(UInt32,c) instead.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in convert(::Type{UInt32}, ::ColorTypes.RGB24) at ./deprecated.jl:50
 in _map_a!(::Images.ScaleMinMax{ColorTypes.RGB24,Float64,Float32}, ::Array{UInt32,2}, ::Images.Image{Float64,2,SubArray{Float64,2,Array{Float64,2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}}) at /home/slava/.julia/v0.5/Images/src/map.jl:492
 in uint32color!(::Array{UInt32,2}, ::Images.Image{Float64,2,SubArray{Float64,2,Array{Float64,2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}}, ::Images.ScaleMinMax{ColorTypes.RGB24,Float64,Float32}) at /home/slava/.julia/v0.5/Images/src/map.jl:673
 in (::ImageView.##30#38)(::Array{UInt32,2}, ::Images.Image{Float64,2,SubArray{Float64,2,Array{Float64,2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}}) at /home/slava/.julia/v0.5/ImageView/src/display.jl:310
 in rerender(::ImageView.ImageCanvas, ::ImageView.ImageSlice2d{Images.Image{Float64,2,SubArray{Float64,2,Array{Float64,2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}}}) at /home/slava/.julia/v0.5/ImageView/src/display.jl:681
 in #view#24(::Array{Any,1}, ::Function, ::Array{Float64,2}) at /home/slava/.julia/v0.5/ImageView/src/display.jl:316
 in view(::Array{Float64,2}) at /home/slava/.julia/v0.5/ImageView/src/display.jl:232
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:64
 in macro expansion at ./REPL.jl:95 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:68
while loading no file, in expression starting on line 184
 29.510494 seconds (22.52 M allocations: 2.978 GB, 0.89% gc time)
(ImageCanvas,ImageSlice2d: zoom = Graphics.BoundingBox(0.0,512.0,0.0,512.0))
**julia> error during Tk callback: 
ERROR: MethodError: no method matching float32(::Float64)**
Closest candidates are:
  float32{C<:ColorTypes.Colorant{T,N}}(::Images.AbstractImage{C<:ColorTypes.Colorant,N}) at /home/slava/.julia/v0.5/Images/src/map.jl:697
  float32{C<:ColorTypes.Colorant{T,N}}(::AbstractArray{C<:ColorTypes.Colorant,N}) at /home/slava/.julia/v0.5/Images/src/map.jl:694
 in contrastgui(::Tk.Tk_Toplevel, ::Images.Image{Float64,2,SubArray{Float64,2,Array{Float64,2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}}, ::ImageView.ImageContrast.ContrastSettings, ::ImageView.##32#40) at /home/slava/.julia/v0.5/ImageView/src/contrast.jl:68
 in contrastgui(::Images.Image{Float64,2,SubArray{Float64,2,Array{Float64,2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}}, ::ImageView.ImageContrast.ContrastSettings, ::Function) at /home/slava/.julia/v0.5/ImageView/src/contrast.jl:28
 in (::ImageView.##31#39)(::String) at /home/slava/.julia/v0.5/ImageView/src/display.jl:312
 in jl_tcl_callback(::Ptr{Void}, ::Ptr{Void}, ::Int32, ::Ptr{Ptr{UInt8}}) at /home/slava/.julia/v0.5/Tk/src/tkwidget.jl:147
 in tcl_doevent(::Timer, ::Int64) at /home/slava/.julia/v0.5/Tk/src/tkwidget.jl:20
 in (::Base.##349#350{Tk.#tcl_doevent,Timer})() at ./event.jl:384

julia> Pkg.status()
6 required packages:
- Colors                        0.6.9
- Gtk                           0.10.2
- ImageCore                     0.0.4
- ImageMagick                   0.1.8
- ImageView                     0.2.0
- TestImages                    0.1.2
  22 additional packages:
- BinDeps                       0.4.5
- Cairo                         0.2.35
- ColorTypes                    0.2.11
- ColorVectorSpace              0.1.11
- Compat                        0.9.2
- Dates                         0.4.4
- FileIO                        0.2.0
- FixedPointNumbers             0.2.1
- Graphics                      0.1.3
- Images                        0.5.12
- IniFile                       0.2.5
- MappedArrays                  0.0.4
- Reexport                      0.0.3
- SHA                           0.2.1
- SIUnits                       0.1.0
- StatsBase                     0.11.1
- TexExtensions                 0.0.3
- Tk                            0.4.0
- URIParser                     0.1.6
- Winston                       0.12.1
- ZipFile                       0.2.6
- Zlib                          0.1.12

julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Prescott)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)

**Comment by timholy** [comment]
Sorry I didn't notice this earlier. Do you know what happened to trigger the error? (For example, did you click on the image somewhere?) With https://github.com/timholy/Images.jl/pull/564 I don't get this error, but I'm not certain whether that really fixes the error or it's just not being triggered for me.

**Comment by timholy** [comment]
I looked at your backtrace more carefully and noticed you were using the contrast GUI. This will be fixed by https://github.com/timholy/Images.jl/pull/565 (`float32` used to be defined in Julia itself to do this, but not in 0.5)

**Comment by postoroniy** [comment]
I didn't click anywhere, just did what is shown in julia> shell

**Comment by postoroniy** [comment]
Can't see this on 0.5, closing issue
