### ISSUE TITLE
view very slow

### ISSUE THREAD

**Issue by my-little-repository** [timholy/ImageView.jl#104]
I just upgraded ImageView and it seems that the view command has become very slow.

    let n = 1000, 
        M = UInt8[convert(UInt8, rand(0:255)) for x=1:n, y=1:n, z=1:3]
      @time ImageView.view(colorim(M), pixelspacing=[1,1])
    end

    julia> 177.311064 seconds (66.00 M allocations: 10.528 GB, 0.86% gc time)
    (ImageCanvas,ImageSlice2d: zoom = Graphics.BoundingBox(0.0,1000.0,0.0,1000.0))

I am sure this was under 1s before the upgrade. I am using  Julia Version 0.5.0 (2016-09-19 18:14 UTC) with ImageView 0.2.0, Images 0.5.14, Cairo 0.2.35.

**Comment by postoroniy** [comment]
not sure that my results are useful, anyway.. 
julia 0.4.6 gave me this
 48.976936 seconds (74.09 M allocations: 598.801 GB, 13.50% gc time)
(ImageCanvas,ImageSlice2d: zoom = Graphics.BoundingBox(0.0,1000.0,0.0,1000.0))

and complained about deprecation as well
WARNING: convert(::Type{UInt32},c::ColorTypes.RGB24) is deprecated, use reinterpret(UInt32,c) instead.

**Comment by timholy** [comment]
I can replicate this. It's already fixed if you use the `fixed-renaming` branches described in https://github.com/timholy/Images.jl/issues/542#issuecomment-254059092. I'm just waiting for a bit more user feedback before I merge that.

**Comment by timholy** [comment]
Closed by #107
