### ISSUE TITLE
Is Contrast  popup gone?

### ISSUE THREAD

**Issue by postoroniy** [timholy/ImageView.jl#109]
can't have access contrast menu on gray images
what's happen with gui contrast?
This - _"Finally, for grayscale images, right-clicking on the image yields a brightness/contrast GUI:"_ does not work.

**Comment by timholy** [comment]
Oh, dear. I'll investigate.

**Comment by postoroniy** [comment]
btw zoom works

**Comment by timholy** [comment]
See #112
