### ISSUE TITLE
ERROR: ArgumentError: FixedPointNumbers.Normed{UInt8,8} is an 8-bit type representing 256 values from 0.0 to 1.0; cannot represent 1151

### ISSUE THREAD

**Issue by postoroniy** [timholy/ImageView.jl#110]
load gray image 
reinterpret as Uint16
run imshow(img) and got this error
ERROR: ArgumentError: FixedPointNumbers.Normed{UInt8,8} is an 8-bit type representing 256 values from 0.0 to 1.0; cannot represent 1151
 in throw_converterror(::Type{FixedPointNumbers.Normed{UInt8,8}}, ::UInt16) at /home/slava/.julia/v0.5/FixedPointNumbers/src/FixedPointNumbers.jl:162
 in _convert(::Type{FixedPointNumbers.Normed{UInt8,8}}, ::Type{UInt8}, ::UInt16) at /home/slava/.julia/v0.5/FixedPointNumbers/src/normed.jl:51
 in Type at /home/slava/.julia/v0.5/ColorTypes/src/types.jl:337 [inlined]
 in convert at /home/slava/.julia/v0.5/ColorTypes/src/conversions.jl:55 [inlined]
 in Type at ./sysimg.jl:53 [inlined]
 in (::ImageView.##22#27)(::UInt16) at /home/slava/.julia/v0.5/ImageView/src/display.jl:56
 in map!(::ImageView.##22#27, ::Array{UInt32,2}, ::SubArray{UInt16,2,Array{UInt16,2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}) at ./abstractarray.jl:1677
 in (::ImageView.##21#26)(::Array{UInt32,2}, ::SubArray{UInt16,2,Array{UInt16,2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}) at /home/slava/.julia/v0.5/ImageView/src/display.jl:56
 in rerender(::ImageView.ImageCanvas, ::ImageView.ImageSlice2d{SubArray{UInt16,2,Array{UInt16,2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}}) at /home/slava/.julia/v0.5/ImageView/src/display.jl:674
 in #imshow#30(::Array{Any,1}, ::Function, ::Array{UInt16,2}) at /home/slava/.julia/v0.5/ImageView/src/display.jl:309
 in imshow(::Array{UInt16,2}) at /home/slava/.julia/v0.5/ImageView/src/display.jl:225

**Comment by postoroniy** [comment]
OR
 x=rand(Int16,128,128);
imshow(x);
and the same error
ERROR: ArgumentError: FixedPointNumbers.Normed{UInt8,8} is an 8-bit type representing 256 values from 0.0 to 1.0; cannot represent 2675
 in throw_converterror(::Type{FixedPointNumbers.Normed{UInt8,8}}, ::Int16) at /home/slava/.julia/v0.5/FixedPointNumbers/src/FixedPointNumbers.jl:162
 in _convert(::Type{FixedPointNumbers.Normed{UInt8,8}}, ::Type{UInt8}, ::Int16) at /home/slava/.julia/v0.5/FixedPointNumbers/src/normed.jl:51
 in Type at /home/slava/.julia/v0.5/ColorTypes/src/types.jl:337 [inlined]
 in convert at /home/slava/.julia/v0.5/ColorTypes/src/conversions.jl:55 [inlined]
 in Type at ./sysimg.jl:53 [inlined]
 in (::ImageView.##22#27)(::Int16) at /home/slava/.julia/v0.5/ImageView/src/display.jl:56
 in map!(::ImageView.##22#27, ::Array{UInt32,2}, ::SubArray{Int16,2,Array{Int16,2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}) at ./abstractarray.jl:1677
 in (::ImageView.##21#26)(::Array{UInt32,2}, ::SubArray{Int16,2,Array{Int16,2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}) at /home/slava/.julia/v0.5/ImageView/src/display.jl:56
 in rerender(::ImageView.ImageCanvas, ::ImageView.ImageSlice2d{SubArray{Int16,2,Array{Int16,2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}}) at /home/slava/.julia/v0.5/ImageView/src/display.jl:674
 in #imshow#30(::Array{Any,1}, ::Function, ::Array{Int16,2}) at /home/slava/.julia/v0.5/ImageView/src/display.jl:309
 in imshow(::Array{Int16,2}) at /home/slava/.julia/v0.5/ImageView/src/display.jl:225

**Comment by timholy** [comment]
Do you require integer-valued images? Have you seen [this section and the next of the documentation](http://juliaimages.github.io/latest/arrays_colors.html#A-consistent-scale-for-floating-point-and-\ )? Note that the more conventional approach forces you into some [very unfortunate inconsistencies](http://scikit-image.org/docs/stable/user_guide/data_types.html).

If you do this:
```julia
julia> x = rand(UInt16, 128, 128);

julia> y = normedview(N0f16, x);

julia> imshow(y)
```
then you get what you're probably expecting. Notice that when you hover over the pixels, their values display on a 0-to-1 scale. At least for me, I very quickly learned to have a better understanding of what `0.11113N0f16` means (it's 11% of the way towards saturating the camera) than 7283 (which doesn't really mean anything except in the context of the maximum value of 65535).

I will fix it so this doesn't return an error, but I'll warn you that the fix is to `clamp01` the images. Consequently integer-valued images display as black for pixels that are 0 and white for pixels that are 1 or higher---probably not what you are expecting.

If you do need to show integer-valued images, ImageView lets you supply manual `clim`s if you want to alter the default scaling:
```julia
julia> imshow(x, clim=(0,typemax(UInt16)))
```

**Comment by postoroniy** [comment]
Yes, I need integer images, where signed integer pixels are intermediate results for understanding " the ways to move(improve) regarding  image processing".
I think it'd be better to make 
```
clim=(0,typemax(UInt16)))
```
if type of data is not in range 0-1, and just warn user about that rather than fall into error.
Thanks.

**Comment by postoroniy** [comment]
```
using ImageFiltering, TestImages,ImageView
img = testimage("mandrill");
imgg = imfilter(img, Kernel.gaussian(3));
imgl = imfilter(img, Kernel.Laplacian())
```
imgg is float64
imgl is float32 for some reason
but
```
imshow(imgg)
(ImageCanvas,ImageSlice2d: zoom = Graphics.BoundingBox(0.0,512.0,0.0,512.0))
```
Looks ok! And
```
imshow(imgl)
ERROR: ArgumentError: FixedPointNumbers.Normed{UInt8,8} is an 8-bit type representing 256 values from 0.0 to 1.0; cannot represent -0.56862754
 in throw_converterror(::Type{FixedPointNumbers.Normed{UInt8,8}}, ::Float32) at /home/slava/.julia/v0.5/FixedPointNumbers/src/FixedPointNumbers.jl:162
 in _convert(::Type{FixedPointNumbers.Normed{UInt8,8}}, ::Type{UInt8}, ::Float32) at /home/slava/.julia/v0.5/FixedPointNumbers/src/normed.jl:51
 in Type at /home/slava/.julia/v0.5/ColorTypes/src/types.jl:337 [inlined]
 in Type at /home/slava/.julia/v0.5/ColorTypes/src/types.jl:338 [inlined] (repeats 2 times)
 in (::ImageView.##22#27)(::ColorTypes.RGB{Float32}) at /home/slava/.julia/v0.5/ImageView/src/display.jl:56
 in map!(::ImageView.##22#27, ::Array{UInt32,2}, ::SubArray{ColorTypes.RGB{Float32},2,Array{ColorTypes.RGB{Float32},2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}) at ./abstractarray.jl:1677
 in (::ImageView.##21#26)(::Array{UInt32,2}, ::SubArray{ColorTypes.RGB{Float32},2,Array{ColorTypes.RGB{Float32},2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}) at /home/slava/.julia/v0.5/ImageView/src/display.jl:56
 in rerender(::ImageView.ImageCanvas, ::ImageView.ImageSlice2d{SubArray{ColorTypes.RGB{Float32},2,Array{ColorTypes.RGB{Float32},2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}}) at /home/slava/.julia/v0.5/ImageView/src/display.jl:674
 in #imshow#30(::Array{Any,1}, ::Function, ::Array{ColorTypes.RGB{Float32},2}) at /home/slava/.julia/v0.5/ImageView/src/display.jl:309
 in imshow(::Array{ColorTypes.RGB{Float32},2}) at /home/slava/.julia/v0.5/ImageView/src/display.jl:225
```
looks completely broken.

**Comment by timholy** [comment]
Sounds good. For an alternative for displaying signed images, see this demo [and function](http://juliaimages.github.io/latest/function_reference.html#ImageCore.scalesigned):

```julia
using Images, TestImages
import ImageView
img = testimage("cameraman")
img1 = img[10:500, 10:500]
img2 = img[12:502, 10:500]
dimg = float(img1)-float(img2)
ss = scalesigned(1)   # replace 1 with whatever scaling you want to encode
cs = colorsigned()
ImageView.imshow(dimg, scalei=x->cs(ss(x)))
```
Result:
![scalesigned](https://cloud.githubusercontent.com/assets/1525481/22445732/721e89ee-e70e-11e6-9ee4-bdfb539d6e91.png)

When you hover over individual pixels you see what the actual value is.

**Comment by timholy** [comment]
But you need #111 merged before that will work. (Thanks for reporting these problems!)
