### ISSUE TITLE
ImageView keeps crashing Julia

### ISSUE THREAD

**Issue by WillShip** [timholy/ImageView.jl#49]
This happens both in Lighttable and the REPL (current version 3.1 Homebrew install on mac osx 10.9.5)

It was happening intermittently before. Now have done a fresh install and it still crashing Julia..

Any advice welcome 
Also once it is working any advice on how to use Imageview within Gtk would be very appreciated e.g.: 
img = imread("filename.jpg")
but then how to convert to an @Image object? and push! the object into a @Window..

julia> using ImageView

2014-10-15 00:33:37.115 julia[25493:507] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7fe2c5b09b90
2014-10-15 00:33:37.117 julia[25493:507] An uncaught exception was raised
2014-10-15 00:33:37.118 julia[25493:507] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7fe2c5b09b90
2014-10-15 00:33:37.118 julia[25493:507] (
    0   CoreFoundation                      0x00007fff8265825c __exceptionPreprocess + 172
    1   libobjc.A.dylib                     0x00007fff8c61ce75 objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff8265b12d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
    3   CoreFoundation                      0x00007fff825b6272 ___forwarding___ + 1010
    4   CoreFoundation                      0x00007fff825b5df8 _CF_forwarding_prep_0 + 120
    5   libtk.dylib                         0x0000000118e29ed6 TkpInit + 459
    6   libtk.dylib                         0x0000000118da7b0f Tk_Init + 1687
    7   ???                                 0x0000000111f45e2a 0x0 + 4596194858
    8   ???                                 0x0000000111f45c12 0x0 + 4596194322
    9   libjulia.dylib                      0x0000000103e66e94 jl_apply_generic + 244
    10  libjulia.dylib                      0x0000000103eb34a1 do_call + 209
    11  libjulia.dylib                      0x0000000103eb1d80 eval + 736
    12  libjulia.dylib                      0x0000000103eb20f7 eval + 1623
    13  libjulia.dylib                      0x0000000103eb31fb eval_body + 667
    14  libjulia.dylib                      0x0000000103eb338a jl_interpret_toplevel_thunk_with + 250
    15  libjulia.dylib                      0x0000000103ec06ef jl_toplevel_eval_flex + 1279
    16  libjulia.dylib                      0x0000000103ec0c84 jl_parse_eval_all + 292
    17  libjulia.dylib                      0x0000000103ec0e7b jl_load + 123
    18  ???                                 0x00000001053f3f13 0x0 + 4382998291
    19  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    20  ???                                 0x00000001053f35d2 0x0 + 4382995922
    21  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    22  libjulia.dylib                      0x0000000103eb34a1 do_call + 209
    23  libjulia.dylib                      0x0000000103eb1d80 eval + 736
    24  libjulia.dylib                      0x0000000103ec06cd jl_toplevel_eval_flex + 1245
    25  libjulia.dylib                      0x0000000103ec0052 jl_eval_module_expr + 690
    26  libjulia.dylib                      0x0000000103ec03bc jl_toplevel_eval_flex + 460
    27  libjulia.dylib                      0x0000000103ec0c84 jl_parse_eval_all + 292
    28  libjulia.dylib                      0x0000000103ec0e7b jl_load + 123
    29  ???                                 0x00000001053f3f13 0x0 + 4382998291
    30  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    31  ???                                 0x00000001053f35d2 0x0 + 4382995922
    32  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    33  libjulia.dylib                      0x0000000103eb34a1 do_call + 209
    34  libjulia.dylib                      0x0000000103eb1d80 eval + 736
    35  libjulia.dylib                      0x0000000103ec06cd jl_toplevel_eval_flex + 1245
    36  libjulia.dylib                      0x0000000103e6c2a0 jl_f_top_eval + 304
    37  ???                                 0x0000000110bb888b 0x0 + 4575692939
    38  ???                                 0x0000000110bb8455 0x0 + 4575691861
    39  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    40  ???                                 0x0000000110bb3258 0x0 + 4575670872
    41  ???                                 0x0000000110bb2db3 0x0 + 4575669683
    42  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    43  libjulia.dylib                      0x0000000103ec1738 eval_import_path_ + 504
    44  libjulia.dylib                      0x0000000103ec043a jl_toplevel_eval_flex + 586
    45  libjulia.dylib                      0x0000000103ec0052 jl_eval_module_expr + 690
    46  libjulia.dylib                      0x0000000103ec03bc jl_toplevel_eval_flex + 460
    47  libjulia.dylib                      0x0000000103ec0c84 jl_parse_eval_all + 292
    48  libjulia.dylib                      0x0000000103ec0e7b jl_load + 123
    49  ???                                 0x00000001053f3f13 0x0 + 4382998291
    50  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    51  ???                                 0x00000001053f35d2 0x0 + 4382995922
    52  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    53  libjulia.dylib                      0x0000000103eb34a1 do_call + 209
    54  libjulia.dylib                      0x0000000103eb1d80 eval + 736
    55  libjulia.dylib                      0x0000000103ec06cd jl_toplevel_eval_flex + 1245
    56  libjulia.dylib                      0x0000000103e6c327 jl_f_top_eval + 439
    57  ???                                 0x0000000110bb888b 0x0 + 4575692939
    58  ???                                 0x0000000110bb8455 0x0 + 4575691861
    59  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    60  ???                                 0x0000000110bb31c2 0x0 + 4575670722
    61  ???                                 0x0000000110bb2db3 0x0 + 4575669683
    62  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    63  libjulia.dylib                      0x0000000103ec1738 eval_import_path_ + 504
    64  libjulia.dylib                      0x0000000103ec043a jl_toplevel_eval_flex + 586
    65  libjulia.dylib                      0x0000000103e6c327 jl_f_top_eval + 439
    66  ???                                 0x00000001109b4a1a 0x0 + 4573579802
    67  ???                                 0x00000001109b4467 0x0 + 4573578343
    68  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    69  ???                                 0x000000011099d5a3 0x0 + 4573484451
    70  libjulia.dylib                      0x0000000103eb991e start_task + 158
    71  libjulia.dylib                      0x0000000103eb83e9 julia_trampoline + 121
    72  julia                               0x0000000103e51a34 start + 52
)
2014-10-15 00:33:37.120 julia[25493:507] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7fe2c5b09b90'
**\* First throw call stack:
(
    0   CoreFoundation                      0x00007fff8265825c **exceptionPreprocess + 172
    1   libobjc.A.dylib                     0x00007fff8c61ce75 objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff8265b12d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
    3   CoreFoundation                      0x00007fff825b6272 ___forwarding**_ + 1010
    4   CoreFoundation                      0x00007fff825b5df8 _CF_forwarding_prep_0 + 120
    5   libtk.dylib                         0x0000000118e29ed6 TkpInit + 459
    6   libtk.dylib                         0x0000000118da7b0f Tk_Init + 1687
    7   ???                                 0x0000000111f45e2a 0x0 + 4596194858
    8   ???                                 0x0000000111f45c12 0x0 + 4596194322
    9   libjulia.dylib                      0x0000000103e66e94 jl_apply_generic + 244
    10  libjulia.dylib                      0x0000000103eb34a1 do_call + 209
    11  libjulia.dylib                      0x0000000103eb1d80 eval + 736
    12  libjulia.dylib                      0x0000000103eb20f7 eval + 1623
    13  libjulia.dylib                      0x0000000103eb31fb eval_body + 667
    14  libjulia.dylib                      0x0000000103eb338a jl_interpret_toplevel_thunk_with + 250
    15  libjulia.dylib                      0x0000000103ec06ef jl_toplevel_eval_flex + 1279
    16  libjulia.dylib                      0x0000000103ec0c84 jl_parse_eval_all + 292
    17  libjulia.dylib                      0x0000000103ec0e7b jl_load + 123
    18  ???                                 0x00000001053f3f13 0x0 + 4382998291
    19  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    20  ???                                 0x00000001053f35d2 0x0 + 4382995922
    21  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    22  libjulia.dylib                      0x0000000103eb34a1 do_call + 209
    23  libjulia.dylib                      0x0000000103eb1d80 eval + 736
    24  libjulia.dylib                      0x0000000103ec06cd jl_toplevel_eval_flex + 1245
    25  libjulia.dylib                      0x0000000103ec0052 jl_eval_module_expr + 690
    26  libjulia.dylib                      0x0000000103ec03bc jl_toplevel_eval_flex + 460
    27  libjulia.dylib                      0x0000000103ec0c84 jl_parse_eval_all + 292
    28  libjulia.dylib                      0x0000000103ec0e7b jl_load + 123
    29  ???                                 0x00000001053f3f13 0x0 + 4382998291
    30  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    31  ???                                 0x00000001053f35d2 0x0 + 4382995922
    32  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    33  libjulia.dylib                      0x0000000103eb34a1 do_call + 209
    34  libjulia.dylib                      0x0000000103eb1d80 eval + 736
    35  libjulia.dylib                      0x0000000103ec06cd jl_toplevel_eval_flex + 1245
    36  libjulia.dylib                      0x0000000103e6c2a0 jl_f_top_eval + 304
    37  ???                                 0x0000000110bb888b 0x0 + 4575692939
    38  ???                                 0x0000000110bb8455 0x0 + 4575691861
    39  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    40  ???                                 0x0000000110bb3258 0x0 + 4575670872
    41  ???                                 0x0000000110bb2db3 0x0 + 4575669683
    42  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    43  libjulia.dylib                      0x0000000103ec1738 eval_import_path_ + 504
    44  libjulia.dylib                      0x0000000103ec043a jl_toplevel_eval_flex + 586
    45  libjulia.dylib                      0x0000000103ec0052 jl_eval_module_expr + 690
    46  libjulia.dylib                      0x0000000103ec03bc jl_toplevel_eval_flex + 460
    47  libjulia.dylib                      0x0000000103ec0c84 jl_parse_eval_all + 292
    48  libjulia.dylib                      0x0000000103ec0e7b jl_load + 123
    49  ???                                 0x00000001053f3f13 0x0 + 4382998291
    50  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    51  ???                                 0x00000001053f35d2 0x0 + 4382995922
    52  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    53  libjulia.dylib                      0x0000000103eb34a1 do_call + 209
    54  libjulia.dylib                      0x0000000103eb1d80 eval + 736
    55  libjulia.dylib                      0x0000000103ec06cd jl_toplevel_eval_flex + 1245
    56  libjulia.dylib                      0x0000000103e6c327 jl_f_top_eval + 439
    57  ???                                 0x0000000110bb888b 0x0 + 4575692939
    58  ???                                 0x0000000110bb8455 0x0 + 4575691861
    59  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    60  ???                                 0x0000000110bb31c2 0x0 + 4575670722
    61  ???                                 0x0000000110bb2db3 0x0 + 4575669683
    62  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    63  libjulia.dylib                      0x0000000103ec1738 eval_import_path_ + 504
    64  libjulia.dylib                      0x0000000103ec043a jl_toplevel_eval_flex + 586
    65  libjulia.dylib                      0x0000000103e6c327 jl_f_top_eval + 439
    66  ???                                 0x00000001109b4a1a 0x0 + 4573579802
    67  ???                                 0x00000001109b4467 0x0 + 4573578343
    68  libjulia.dylib                      0x0000000103e66e28 jl_apply_generic + 136
    69  ???                                 0x000000011099d5a3 0x0 + 4573484451
    70  libjulia.dylib                      0x0000000103eb991e start_task + 158
    71  libjulia.dylib                      0x0000000103eb83e9 julia_trampoline + 121
    72  julia                               0x0000000103e51a34 start + 52
)
libc++abi.dylib: terminating with uncaught exception of type NSException

signal (6): Abort trap: 6
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Abort trap: 6

**Comment by timholy** [comment]
The Gtk migration is done.
