### ISSUE TITLE
ERROR: `width` has no method matching width(::GtkCanvas)

### ISSUE THREAD

**Issue by philtomson** [timholy/ImageView.jl#62]
I've been using the gtk branch of ImageView in order to avoid a different Tk bug that I was experiencing on Ubuntu 12.04 (it was suggested to try the gtk branch and also suggested that the gtk branch would become the main branch soon.)

Today, I did a Pkg.update() (which probably wasn't a very good idea as I'm using this special gtk branch of ImageView) and after that I had some problems. I went and completely reinstalled the gtk branch of ImageView and this is what I'm getting now:

julia> using ImageView, Images

julia> using TestImages

julia> img = testimage("mandrill")
RGB Image with:
  data: 512x512 Array{RGB{UfixedBase{Uint8,8}},2}
  properties:
    IMcs: RGB
    spatialorder:  x y
    pixelspacing:  1 1

julia> view(img)
(ImageCanvas,ImageSlice2d: zoom = BoundingBox(0.0,512.0,0.0,512.0))

julia> ERROR: `width` has no method matching width(::GtkCanvas)
 in setbb! at /home/phil/.julia/v0.3/ImageView/src/display.jl:80
 in resize at /home/phil/.julia/v0.3/ImageView/src/display.jl:582
 in anonymous at /home/phil/.julia/v0.3/ImageView/src/display.jl:420
 in draw at /home/phil/.julia/v0.3/Gtk/src/cairo.jl:72
 in notify_resize at /home/phil/.julia/v0.3/Gtk/src/cairo.jl:52

Is there some version mismatch now between Cairo, GTK and ImageView?

**Comment by timholy** [comment]
Is your Gtk using the new Graphics package? What does `Pkg.status("Gtk")` say?

You may also need to update this branch to use the Graphics package rather than Base.Graphics.

**Comment by philtomson** [comment]
julia> Pkg.status("Gtk")
ERROR: `status` has no method matching status(::ASCIIString)

I'm running Julia 0.3.6 if that makes a difference.

**Comment by philtomson** [comment]
julia> versioninfo(true) 

 - Gtk                           0.8.0

**Comment by timholy** [comment]
Can you try updating this branch to use the new Graphics package? Let me know what happens.
