### ISSUE TITLE
"Can't find a usable init.tcl"

### ISSUE THREAD

**Issue by joa-quim** [timholy/ImageView.jl#66]
Hi,
After a Pkg.update(), which updated

`INFO: Upgrading ImageView: v0.1.9 => v0.1.12`

I'm now getting this error (that I remember to have seen other people complaining before)
This is Win64 julia 0.3.4 (but same error in v0.4dev)

`ERROR: TclError("error initializing Tcl: Can't find a usable init.tcl in the following directories: \n    {C:\\programs\\WinPython2.7.6.3_64\\python-2.7.6.amd64\\share\\tcl} C:/programs/WinPython2.7.6.3_64/python-2.7.6.amd64/share/tcl8.5 C:/programs/WinPython2.7.6.3_64/python-2.7.6.amd64/lib/tcl8.5 C:/programs/julia-0.3.4/lib/tcl8.5 C:/programs/lib/tcl8.5 C:/programs/julia-0.3.4/library C:/programs/library C:/programs/tcl8.5.2/library C:/tcl8.5.2/library\n\n\n\nThis probably means that Tcl wasn't installed properly.\n")`

**Comment by timholy** [comment]
Looks like a Tk.jl bug. Can you report this there?

**Comment by joa-quim** [comment]
There is one issue there with the same title, but it's closed. How do I reopen it?

**Comment by timholy** [comment]
I don't think you can without commit privileges, but you could start a new one.
