### ISSUE TITLE
Setting z slice to show

### ISSUE THREAD

**Issue by cbecker** [timholy/ImageView.jl#68]
Hi Tim, I've been looking at the code but still haven't figured it out, I suppose there is an easy way to do this.

I tried with 

```
view( grayim(rand((10,10,10))), zindex=5 )
```

but I still get the viewer starting at `z=1`. Also, is there a way to set the value of `z` after creating the canvas?

I tried the following with no success

```
i1,i2=view( grayim(rand((10,10,10))))
i1.navigationstate.z=5
ImageView.reslice(i1,i2,i1.navigationstate)
```

thanks!

EDIT: I see now that the code above works, but the slider is still stuck at `z=1`

**Comment by timholy** [comment]
Should be fixed with the new ImageView (uses Reactive).
