### ISSUE TITLE
LoadError: invalid union type

### ISSUE THREAD

**Issue by joa-quim** [timholy/ImageView.jl#72]
Hi, 
With a nightly build of 0.4

julia> using ImageView, Images
Warning: New definition
    convert(Type{Images.Image{Cdest<:Union(Color.AbstractAlphaColorValue{C<:Colo
r.ColorValue{T},T<:Real},Color.ColorValue{T}),N,A<:AbstractArray{T,N}}}, Images.
AbstractImageDirect{Csrc<:Union(Color.AbstractAlphaColorValue{C<:Color.ColorValu
e{T},T<:Real},Color.ColorValue{T}),N}) at C:\j\.julia\v0.4\Images\src\core.jl:22
9
is ambiguous with:
    convert(Type{Images.Image{T,N,A<:AbstractArray{T,N}}}, Images.Image{T,N,A<:A
bstractArray{T,N}}) at C:\j\.julia\v0.4\Images\src\core.jl:202.

To fix, define
    convert(Type{Images.Image{_<:Union(Color.AbstractAlphaColorValue{C<:Color.Co
lorValue{T},T<:Real},Color.ColorValue{T}),N,A<:AbstractArray{T,N}}}, Images.Imag
e{_<:Union(Color.AbstractAlphaColorValue{C<:Color.ColorValue{T},T<:Real},Color.C
olorValue{T}),N,A<:AbstractArray{T,N}})
before the new definition.

ERROR: LoadError: LoadError: invalid union type
 in include at boot.jl:252

**Comment by ayakimovich** [comment]
I wonder whether this could be connected with the error I'm getting in nightly Travis testing of MatlabCompat dev branch:

ERROR: LoadError: LoadError: LoadError: LoadError: LoadError: syntax: "ID::Int=0" inside type definition is reserved
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:55
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in anonymous at no file:36
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:52
 in include at ./boot.jl:254
 in include_from_node1 at loading.jl:133
 in process_options at ./client.jl:306
 in _start at ./client.jl:406
while loading /home/travis/.julia/v0.4/Tk/src/tkwidget.jl, in expression starting on line 125
while loading /home/travis/.julia/v0.4/Tk/src/Tk.jl, in expression starting on line 35
while loading /home/travis/.julia/v0.4/MatlabCompat/src/MatlabCompat/imagetools.jl, in expression starting on line 48
while loading /home/travis/.julia/v0.4/MatlabCompat/src/MatlabCompat.jl, in expression starting on line 35
while loading /home/travis/.julia/v0.4/MatlabCompat/test/runtests.jl, in expression starting on line 1

(https://travis-ci.org/MatlabCompat/MatlabCompat.jl/jobs/69903907)[https://travis-ci.org/MatlabCompat/MatlabCompat.jl/jobs/69903907]

It basically fails whenever I;m saying: 
using ImageView

Any help on fixing this is much appreciated.

**Comment by timholy** [comment]
@joa-quim, sorry I didn't notice this. For me I get none of those errors with a current julia build and current master of the packages. ImageView is up-to-date (the release is the same as master); Images is a little behind in terms of its release, so I'm just now tagging a new Images release just in case that's the issue. Are you still having problems?

**Comment by timholy** [comment]
@ayakimovich, you're running into Tk bug https://github.com/JuliaLang/Tk.jl/issues/105. The workaround currently is to check out the `ob/fix` branch. Someone who has more time available than me should figure out a real solution to that problem (either get that branch merged or come up with some other solution).

CC @carnaval, @JeffBezanson (Jeff, it was a julia commit of yours that likely broke Tk).

**Comment by ayakimovich** [comment]
Many thanks for looking into this @timholy. @Jeffbezanson, @carnaval please check out the pull request from @ewiger:
https://github.com/JuliaLang/Tk.jl/pull/106
