### ISSUE TITLE
Selections

### ISSUE THREAD

**Issue by Jakki42** [timholy/ImageView.jl#75]
It would be nice to be able to make (rectangular) selections from the images. When I use imageJ I often have to select interactively a subsection of an image and then do measurements on that. As far as I know it's not currently possible with ImageView.jl?

**Comment by timholy** [comment]
You can do that now. See https://github.com/timholy/ImageView.jl#programmatic-usage and check the two outputs.

**Comment by Jakki42** [comment]
Ah, imgslice.zoombb :-)

Thank you!
