### ISSUE TITLE
Saving displayed image to file?

### ISSUE THREAD

**Issue by cbecker** [timholy/ImageView.jl#78]
Hi Tim, I am wondering if there is an easy way to save the contents that are currently being displayed by ImageView to a png or any other image format. I love how easy it is to draw overlays/text/boxes to an ImageView canvas, 

I tried the following but it won't save the annotations, as I think I am only capturing the image part:
```julia
using Cairo
i1,i2 = ImageView.view( whatever_img )
Cairo.write_to_png(i1.surface, "/tmp/test.png")
```

thanks.

**Comment by rsrock** [comment]
See if this helps: #28

**Comment by cbecker** [comment]
Thanks! I should've checked before, works perfectly.
