### ISSUE TITLE
Window flickering with float64 color values

### ISSUE THREAD

**Issue by my-little-repository** [timholy/ImageView.jl#83]
Related to #65 and #53. The following code displays a tiny colored square in a  window.

      julia> view(Image(Color.RGB[Color.color(@sprintf("\#%2s%2saa",x,y)) for x = 10:90, y=10:90]), pixelspacing=[1,1])

When I mouse over the window, it flickers and tries to extend far to the right, sometimes with success.
Resizing the window stops the flickering.

Apparently, this is because the Float64 color values displayed at the bottom of the image are changing when I mouse over and thus their width are altered, triggering a window resizing.The bug does not appear with Ufixed8 values, they do not need so much space to display. This may be specific to my GUI (qt on kde on linux), but rsrock reported some similar problem on OSX in #65.

Is there a way to disable the display of color values at the bottom of the screen?

**Comment by timholy** [comment]
Fixed. CC @rsrock re #65.
