### ISSUE TITLE
Memory allocation persistence after destroying window?

### ISSUE THREAD

**Issue by macrintr** [timholy/ImageView.jl#89]
When I create and display an ImageCanvas and ImageSlice2d using `view` it seems to allocate a portion of memory that persists even when I close it. On my machine, it's around 16MB for an 8MB image, and it seems to scale linearly. 

Noting system memory usage (like on `htop`) before and after, see if you can recreate what I'm talking about with the following code:

```
@time imgc, img2 = view(rand(1000,1000))
destroy(toplevel(imgc))
```

Is there a way to remove that memory allocation after the window is destroyed?

**Comment by LMescheder** [comment]
The following issue #32 seems related. Strange tough that it was closed, since circumventing the problem requires setting the undocumented parameter `interactive=false` in the call to `view`...

**Comment by timholy** [comment]
With the new ImageView this doesn't grow in memory:

```julia
julia> for i = 1:100
           imgdct = imshow(rand(1000,1000));
           Gtk.destroy(imgdct["gui"]["window"])
           imgdct = 0
           gc()
       end
```
