### ISSUE TITLE
Error using AnnotationPoints with vector of tuples

### ISSUE THREAD

**Issue by rsrock** [timholy/ImageView.jl#92]
Running some old code here on Julia 0.4.6, and running into this:

```
julia> using Images, ImageView
WARNING: requiring "Dates" in module "Winston" did not define a corresponding module.
WARNING: module Winston should explicitly import * from Base
WARNING: could not import Images.scaleinfo into ImageView

julia> ann_spots = [(1., 2.), (3., 4.)]
2-element Array{Tuple{Float64,Float64},1}:
 (1.0,2.0)
 (3.0,4.0)

julia> ImageView.AnnotationPoints(ann_spots)
ERROR: MethodError: `convert` has no method matching convert(::Type{ImageView.AnnotationPoints{T}}, ::Array{Tuple{Float64,Float64},1})
This may have arisen from a call to the constructor ImageView.AnnotationPoints{T}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  ImageView.AnnotationPoints{T}(::T, ::Float64, ::Float64, ::Float64, ::Char, ::ColorTypes.Color{T,N}, ::Float64, ::ColorTypes.Color{T,N}, ::Bool)
  call{T}(::Type{T}, ::Any)
  convert{T}(::Type{T}, ::T)
  ...
 in call at essentials.jl:56
```

I can't see why [this line](https://github.com/timholy/ImageView.jl/blob/99c78b960ad779cfcb90f35ef328e3ead52c743b/src/annotations.jl#L86) isn't getting picked up.  I do seem to have a vector of Tuples here.  Any ideas?

**Comment by timholy** [comment]
Maybe try getting rid of that `Type`?

**Comment by rsrock** [comment]
That `Type` that I missed the last dozen times that I read that line?  Yes, that helps. :smile:

**Comment by timholy** [comment]
It's often fiendishly difficult to navigate ones' way through those type specifications.

**Comment by timholy** [comment]
Do you think this is something that changed during the course of 0.4?

**Comment by rsrock** [comment]
The code that triggered this issue hadn't been touched since 0.3, so it's hard to tell.

**Comment by rsrock** [comment]
I'll work on a fix, by the way.

**Comment by timholy** [comment]
Thanks!
