### ISSUE TITLE
Status of Gtk version?

### ISSUE THREAD

**Issue by AStupidBear** [timholy/ImageView.jl#97]

**Comment by timholy** [comment]
I'm rewriting Images now, ImageView comes after that is done.

I do have a Gtk-based viewer that I use privately, but it's a small thing that doesn't support much of the functionality of ImageView. If people really need something now I can post it, but I will not promise to support it---it's "take it as-is", add features or fix bugs yourself.

**Comment by bjarthur** [comment]
will the Gtk version supplant this Tk version?  either way, is it worth fixing these deprecations?

```
julia> using ImageView
WARNING: Base.WORD_SIZE is deprecated.
  likely near /Users/arthurb/.julia/v0.5/Tk/src/tkwidget.jl:269
WARNING: `@linux_only` is deprecated, use `@static if is_linux()` instead
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in depwarn(::String, ::Symbol) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in @linux_only(::Any) at ./deprecated.jl:500
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in require(::Symbol) at ./loading.jl:415
 in require(::Symbol) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:64
 in macro expansion at ./REPL.jl:95 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:68
while loading /Users/arthurb/.julia/v0.5/ImageView/src/display.jl, in expression starting on line 17

julia> Pkg.installed("ImageView")
v"0.1.20+"

julia> VERSION
v"0.5.0"
```

**Comment by timholy** [comment]
Thanks for fixing the deprecations!

It's a timely question, since the Images rewrite is almost to the finish line---before merging it to master, I plan to at least start on the ImageView rewrite in case I discover more changes that need to be made to support ImageView. My intention is that the Gtk version would supplant the Tk version. Is supporting both toolkits a priority?

**Comment by bjarthur** [comment]
supporting both is not a priority for me.  i just wanted to know whether it was worth the time to fix the deprecations.  went ahead and did it anyway because they bothered me.

**Comment by timholy** [comment]
The Gtk version is released.
